#!/bin/bash
# commande clt qui vide le répertoire trash de tout son contenu

# Vérifie qu'il y a exactement un argument
if [ $# -ne 0 ]; then
    echo "Usage: $0"
    exit 1
fi

rm -iR ~/Bureau/trash/*
